// This file was generated by Prisma, and assumes you run Prisma commands using `bun --bun run prisma [command]`.
import { defineConfig } from "prisma/config";
import { config } from "dotenv";

config({ path: ".env" });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "bun src/seed.ts",
  },
  datasource: {
    url: process.env.DATABASE_URL!,
  },
});
